# External Secrets Operator for Kubernetes
# Provides integration between Kubernetes Secrets and HashiCorp Vault
# This manifest deploys the External Secrets Operator controller

---
# External Secrets Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    name: external-secrets

---
# ServiceAccount for External Secrets Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets

---
# ClusterRole for External Secrets Operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets
rules:
- apiGroups: ["externalsecrets.io"]
  resources: ["externalsecrets", "secretstores", "clustersecretstores"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["externalsecrets.io"]
  resources: ["externalsecrets/status", "secretstores/status", "clustersecretstores/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

---
# ClusterRoleBinding for External Secrets Operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets
subjects:
- kind: ServiceAccount
  name: external-secrets
  namespace: external-secrets

---
# Deployment for External Secrets Operator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-secrets
    spec:
      serviceAccountName: external-secrets
      containers:
      - name: external-secrets
        image: ghcr.io/external-secrets/external-secrets:v0.9.9
        imagePullPolicy: IfNotPresent
        command:
        - external-secrets
        - --metrics-addr=0.0.0.0:8080
        - --health-addr=0.0.0.0:8081
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8081
          name: health
        env:
        - name: EXTERNAL_SECRETS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            drop:
            - ALL

---
# HorizontalPodAutoscaler for External Secrets Operator
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: external-secrets
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---
# Service for External Secrets Operator metrics
apiVersion: v1
kind: Service
metadata:
  name: external-secrets
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
spec:
  selector:
    app.kubernetes.io/name: external-secrets
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  - name: health
    port: 8081
    targetPort: 8081
  type: ClusterIP

---
# ResourceQuota for external-secrets namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: external-secrets-quota
  namespace: external-secrets
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "512Mi"
    limits.cpu: "2"
    limits.memory: "1Gi"
    pods: "10"

---
# LimitRange for external-secrets namespace
apiVersion: v1
kind: LimitRange
metadata:
  name: external-secrets-limits
  namespace: external-secrets
spec:
  limits:
  - type: Pod
    max:
      cpu: "1"
      memory: "512Mi"
    min:
      cpu: "10m"
      memory: "32Mi"
  - type: Container
    max:
      cpu: "1"
      memory: "512Mi"
    min:
      cpu: "10m"
      memory: "32Mi"
    default:
      cpu: "100m"
      memory: "128Mi"
    defaultRequest:
      cpu: "50m"
      memory: "64Mi"

---
# NetworkPolicy for External Secrets Operator
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: external-secrets-network-policy
  namespace: external-secrets
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: external-secrets
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8081
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: vault
    ports:
    - protocol: TCP
      port: 8200
  - to:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443

---
# PodDisruptionBudget for External Secrets Operator
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: external-secrets-pdb
  namespace: external-secrets
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
