# PepperJarvis Agent - HashiCorp Vault Secrets Management
# This manifest sets up a secure secrets management system using HashiCorp Vault
# Secrets are stored securely and access is controlled via RBAC

---
# Vault Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    name: vault

---
# Vault ConfigMap for initial setup
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault-config.hcl: |
    ui = true

    listener "tcp" {
      address       = "0.0.0.0:8200"
      tls_disable   = false
      tls_cert_file = "/vault/tls/vault.crt"
      tls_key_file  = "/vault/tls/vault.key"
    }

    storage "file" {
      path = "/vault/data"
    }

---
# ServiceAccount for Vault
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: vault

---
# ClusterRole for Vault
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault
rules:
- apiGroups: [""]
  resources: ["serviceaccounts", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
# ClusterRoleBinding for Vault
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault
subjects:
- kind: ServiceAccount
  name: vault
  namespace: vault

---
# Vault StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: vault
spec:
  serviceName: vault
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault
      containers:
      - name: vault
        image: vault:1.15.0
        imagePullPolicy: IfNotPresent
        command:
        - vault
        - server
        - -config=/vault/config/vault-config.hcl
        ports:
        - containerPort: 8200
          name: vault
        env:
        - name: VAULT_ADDR
          value: "https://0.0.0.0:8200"
        - name: VAULT_API_ADDR
          value: "https://vault.vault.svc.cluster.local:8200"
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
        - name: vault-data
          mountPath: /vault/data
        - name: vault-tls
          mountPath: /vault/tls
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: vault-config
        configMap:
          name: vault-config
      - name: vault-tls
        secret:
          secretName: vault-tls
          optional: true
  volumeClaimTemplates:
  - metadata:
      name: vault-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: exoscale-sbs
      resources:
        requests:
          storage: 10Gi

---
# Vault Service
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
spec:
  clusterIP: None
  selector:
    app: vault
  ports:
  - port: 8200
    targetPort: 8200
    name: vault

---
# Vault Service (ClusterIP for access)
apiVersion: v1
kind: Service
metadata:
  name: vault-svc
  namespace: vault
spec:
  selector:
    app: vault
  ports:
  - port: 8200
    targetPort: 8200
  type: ClusterIP

---
# ServiceAccount for PepperJarvis Agent (for Vault auth)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pepperjavis-agent
  namespace: pepperjavis

---
# Role for PepperJarvis Agent to read secrets from ExternalSecrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pepperjavis-secrets-reader
  namespace: pepperjavis
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
  resourceNames:
  - "postgres-secret"
  - "minio-secret"
  - "pepperjavis-api-key"
  - "pepperjavis-aws-credentials"
  - "pepperjavis-llm-key"

---
# RoleBinding for PepperJarvis Agent
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pepperjavis-secrets-reader-binding
  namespace: pepperjavis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pepperjavis-secrets-reader
subjects:
- kind: ServiceAccount
  name: pepperjavis-agent
  namespace: pepperjavis

---
# Service Account for External Secrets Operator to read from Vault
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-operator
  namespace: external-secrets

---
# ClusterRole for External Secrets Operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-operator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["externalsecrets.io"]
  resources: ["secretstores", "clustersecretstores"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["externalsecrets.io"]
  resources: ["externalsecrets"]
  verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding for External Secrets Operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-operator
subjects:
- kind: ServiceAccount
  name: external-secrets-operator
  namespace: external-secrets

---
# ClusterSecretStore for Vault (accessible to all namespaces)
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-store
spec:
  provider:
    vault:
      server: "https://vault-svc.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets-operator"

---
# SecretStore for Vault in pepperjavis namespace
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-store
  namespace: pepperjavis
spec:
  provider:
    vault:
      server: "https://vault-svc.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "pepperjavis-agent"

---
# ExternalSecret for PostgreSQL credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: pepperjavis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
    template:
      type: Opaque
      stringData:
        password: "{{ .postgres_password }}"
        username: "{{ .postgres_username }}"
        host: "{{ .postgres_host }}"
        port: "{{ .postgres_port }}"
        database: "{{ .postgres_database }}"
  data:
  - secretKey: postgres_password
    remoteRef:
      key: database/postgres
      property: password
  - secretKey: postgres_username
    remoteRef:
      key: database/postgres
      property: username
  - secretKey: postgres_host
    remoteRef:
      key: database/postgres
      property: host
  - secretKey: postgres_port
    remoteRef:
      key: database/postgres
      property: port
  - secretKey: postgres_database
    remoteRef:
      key: database/postgres
      property: database

---
# ExternalSecret for MinIO credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secret
  namespace: pepperjavis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: minio-secret
    creationPolicy: Owner
    template:
      type: Opaque
      stringData:
        password: "{{ .minio_password }}"
        username: "{{ .minio_username }}"
        endpoint: "{{ .minio_endpoint }}"
        access_key: "{{ .minio_access_key }}"
        secret_key: "{{ .minio_secret_key }}"
  data:
  - secretKey: minio_password
    remoteRef:
      key: storage/minio
      property: password
  - secretKey: minio_username
    remoteRef:
      key: storage/minio
      property: username
  - secretKey: minio_endpoint
    remoteRef:
      key: storage/minio
      property: endpoint
  - secretKey: minio_access_key
    remoteRef:
      key: storage/minio
      property: access_key
  - secretKey: minio_secret_key
    remoteRef:
      key: storage/minio
      property: secret_key

---
# ExternalSecret for API Keys and credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pepperjavis-api-key
  namespace: pepperjavis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: pepperjavis-api-key
    creationPolicy: Owner
    template:
      type: Opaque
      stringData:
        api_key: "{{ .api_key }}"
        api_secret: "{{ .api_secret }}"
        jwt_secret: "{{ .jwt_secret }}"
  data:
  - secretKey: api_key
    remoteRef:
      key: application/pepperjavis
      property: api_key
  - secretKey: api_secret
    remoteRef:
      key: application/pepperjavis
      property: api_secret
  - secretKey: jwt_secret
    remoteRef:
      key: application/pepperjavis
      property: jwt_secret

---
# ExternalSecret for AWS credentials (if needed)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pepperjavis-aws-credentials
  namespace: pepperjavis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: pepperjavis-aws-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      stringData:
        aws_access_key_id: "{{ .aws_access_key_id }}"
        aws_secret_access_key: "{{ .aws_secret_access_key }}"
        aws_region: "{{ .aws_region }}"
  data:
  - secretKey: aws_access_key_id
    remoteRef:
      key: cloud/aws
      property: access_key_id
  - secretKey: aws_secret_access_key
    remoteRef:
      key: cloud/aws
      property: secret_access_key
  - secretKey: aws_region
    remoteRef:
      key: cloud/aws
      property: region

---
# ExternalSecret for LLM API Keys
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pepperjavis-llm-key
  namespace: pepperjavis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: pepperjavis-llm-key
    creationPolicy: Owner
    template:
      type: Opaque
      stringData:
        openai_api_key: "{{ .openai_api_key }}"
        anthropic_api_key: "{{ .anthropic_api_key }}"
        azure_openai_key: "{{ .azure_openai_key }}"
  data:
  - secretKey: openai_api_key
    remoteRef:
      key: llm/openai
      property: api_key
  - secretKey: anthropic_api_key
    remoteRef:
      key: llm/anthropic
      property: api_key
  - secretKey: azure_openai_key
    remoteRef:
      key: llm/azure
      property: api_key

---
# NetworkPolicy for Vault access
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vault-access-policy
  namespace: vault
spec:
  podSelector:
    matchLabels:
      app: vault
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: external-secrets
    - namespaceSelector:
        matchLabels:
          name: pepperjavis
    ports:
    - protocol: TCP
      port: 8200

---
# NetworkPolicy for External Secrets Operator to access Vault
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: external-secrets-to-vault
  namespace: external-secrets
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: vault
    ports:
    - protocol: TCP
      port: 8200
