# PepperJarvis Agent - Complete Observability & Failsafes
# Prometheus + AlertManager + Service Monitoring for runaway process detection

---
# Prometheus ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: pepperjavis
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: 'pepperjavis-agent'
        environment: 'production'

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093

    rule_files:
    - /etc/prometheus/rules/*.yml

    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']

    - job_name: 'pepperjavis-agent'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - pepperjavis
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: pepperjavis-agent
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        action: keep
        regex: "8000"

    - job_name: 'postgres'
      static_configs:
      - targets: ['postgres:5432']
      relabel_configs:
      - source_labels: [__scheme__]
        target_label: __scheme__
        replacement: 'postgres'

    - job_name: 'redis'
      static_configs:
      - targets: ['redis:6379']

    - job_name: 'minio'
      metrics_path: /minio/v2/metrics/cluster
      static_configs:
      - targets: ['minio:9000']

  alerts.yml: |
    groups:
    - name: pepperjavis-alerts
      interval: 30s
      rules:

      # CPU Runaway Detection
      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total[5m]) > 0.8
        for: 2m
        labels:
          severity: warning
          component: runaway-detection
        annotations:
          summary: "High CPU usage detected on {{ $labels.pod_name }}"
          description: "Pod {{ $labels.pod_name }} is using {{ $value | humanizePercentage }} CPU"

      - alert: CriticalCPUUsage
        expr: rate(container_cpu_usage_seconds_total[5m]) > 0.95
        for: 30s
        labels:
          severity: critical
          component: runaway-detection
        annotations:
          summary: "CRITICAL: CPU runaway detected on {{ $labels.pod_name }}"
          description: "Pod {{ $labels.pod_name }} is using {{ $value | humanizePercentage }} CPU - Killing in 30s"

      # Memory Runaway Detection
      - alert: HighMemoryUsage
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.8
        for: 2m
        labels:
          severity: warning
          component: runaway-detection
        annotations:
          summary: "High memory usage on {{ $labels.pod_name }}"
          description: "Pod {{ $labels.pod_name }} is using {{ $value | humanizePercentage }} of its limit"

      - alert: CriticalMemoryUsage
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.95
        for: 30s
        labels:
          severity: critical
          component: runaway-detection
        annotations:
          summary: "CRITICAL: Memory runaway detected on {{ $labels.pod_name }}"
          description: "Pod {{ $labels.pod_name }} is using {{ $value | humanizePercentage }} of its limit - OOMKill imminent"

      # Pod RestartLoop Detection
      - alert: PodCrashLooping
        expr: rate(kube_pod_container_status_restarts_total[15m]) > 0.5
        for: 1m
        labels:
          severity: critical
          component: failsafe
        annotations:
          summary: "Pod {{ $labels.pod }} is crash looping"
          description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has restarted {{ $value }} times in 15 minutes"

      # Database Availability
      - alert: PostgresDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL endpoint is not responding"

      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis endpoint is not responding"

      - alert: MinIODown
        expr: up{job="minio"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "MinIO is down"
          description: "MinIO endpoint is not responding"

      # Storage Issues
      - alert: PersistentVolumeHighUsage
        expr: (kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes) > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PVC {{ $labels.persistentvolumeclaim }} is 85% full"
          description: "PVC {{ $labels.persistentvolumeclaim }} has {{ $value | humanizePercentage }} used"

      - alert: PersistentVolumeCritical
        expr: (kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes) > 0.95
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "PVC {{ $labels.persistentvolumeclaim }} is 95% full"
          description: "PVC {{ $labels.persistentvolumeclaim }} has {{ $value | humanizePercentage }} used - IMMEDIATE ACTION REQUIRED"

      # Node Issues
      - alert: NodeNotReady
        expr: kube_node_status_condition{condition="Ready",status="true"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Node {{ $labels.node }} is not ready"
          description: "Node {{ $labels.node }} has been NotReady for 5 minutes"

---
# AlertManager ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: pepperjavis
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'default'
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h

      routes:
      - match:
          severity: critical
          component: runaway-detection
        receiver: 'runaway-killer'
        group_wait: 5s
        repeat_interval: 5m

      - match:
          severity: critical
        receiver: 'pagerduty'
        group_wait: 5s
        repeat_interval: 1h

    receivers:
    - name: 'default'
      webhook_configs:
      - url: http://alert-handler:8080/webhooks/default

    - name: 'runaway-killer'
      webhook_configs:
      - url: http://alert-handler:8080/webhooks/kill-runaway
        send_resolved: false

    - name: 'pagerduty'
      webhook_configs:
      - url: http://alert-handler:8080/webhooks/pagerduty

---
# Prometheus Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: pepperjavis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        imagePullPolicy: IfNotPresent
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention.time=30d'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
        - '--web.enable-lifecycle'
        ports:
        - containerPort: 9090
          name: prometheus
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: prometheus-rules
          mountPath: /etc/prometheus/rules
        - name: prometheus-data
          mountPath: /prometheus
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10

      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-rules
        configMap:
          name: prometheus-config
      - name: prometheus-data
        emptyDir: {}

---
# AlertManager Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: pepperjavis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        imagePullPolicy: IfNotPresent
        args:
        - '--config.file=/etc/alertmanager/alertmanager.yml'
        - '--storage.path=/alertmanager'
        ports:
        - containerPort: 9093
          name: alertmanager
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager
        - name: alertmanager-data
          mountPath: /alertmanager
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

      volumes:
      - name: alertmanager-config
        configMap:
          name: alertmanager-config
      - name: alertmanager-data
        emptyDir: {}

---
# Prometheus Service
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: pepperjavis
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP

---
# AlertManager Service
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: pepperjavis
spec:
  selector:
    app: alertmanager
  ports:
  - port: 9093
    targetPort: 9093
  type: ClusterIP

---
# ServiceAccount for Prometheus
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: pepperjavis

---
# ClusterRole for Prometheus
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding for Prometheus
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: pepperjavis
